spring:
  application:
    name: customer-service
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: refresh
datasource:
  url: jdbc:oracle:thin:@localhost:1521:XE
  username: system
  password: admin
  driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
